### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by JavaRockstar** [UltimateHackers/anoNmap#2]
You have copied this software from https://github.com/vishwaraj/fbxspa/blob/master/fbxspa.py but your code is not as clean.

**Comment by UltimateHackers** [comment]
Mr. Copyright Guardian,
When I created this tool, I didn't even if such thing already exists.
I found a vulnerability and wrote a script for it, thats it.
If that bothers you then you can contact that tools author and he will decide if the code is copied or not.
Regards.
